name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: steup nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install dependencies
        run: pnpm install
      - name: run tests
        run: pnpm run test
  DockerBuild:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
  VercelBuild:
    needs: Test
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: steup nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install vercel cli
        run: pnpm install -g vercel
      - name: install dependencies
        run: pnpm install
      - name: pull vercel project settings
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: build vercel
        run: vercel build --token ${{ secrets.VERCEL_TOKEN }}
      - name: upload vercel build
        uses: actions/upload-artifact@v4
        with:
          name: vercel-build-output
          path: dist
  VercelDeploye:
    needs: VercelBuild
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: steup nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install vercel cli
        run: pnpm install -g vercel
      - name: download build output
        uses: actions/download-artifact@v4
        with:
          name: vercel-build-output
          path: .vercel/output
      - name: deploye to vercel
        id: deploye
        run: |
          URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --yes)
          echo "deployment_url=$URL" >> $GITHUB_OUTPUT
      - name: get deployment url
        run: echo "deployment url => ${{ steps.deploye.outputs.deployment_url }}"
