name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: steup nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install depencies
        run: pnpm install
      - name: run tests
        run: pnpm run test
